create table public.blogs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  author bigint not null,
  content text null,
  image text null,
  constraint blogs_pkey primary key (id),
  constraint blogs_author_fkey foreign KEY (author) references users (id)
) TABLESPACE pg_default;

create table public.chats_messages (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  sender_id bigint null,
  receiver_id bigint null,
  content text null,
  content_type smallint null,
  constraint chats_messages_pkey primary key (id),
  constraint chats_messages_receiver_id_fkey foreign KEY (receiver_id) references users (id),
  constraint chats_messages_sender_id_fkey foreign KEY (sender_id) references users (id)
) TABLESPACE pg_default;

create table public.follows (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  following_id bigint null,
  follower_id bigint null,
  constraint follows_pkey primary key (id),
  constraint fk_follower foreign KEY (follower_id) references users (id),
  constraint fk_following foreign KEY (following_id) references users (id)
) TABLESPACE pg_default;

create table public.group_members (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  group_id bigint null,
  member_id bigint null,
  is_admin boolean null,
  constraint group_members_pkey primary key (id),
  constraint group_members_group_id_fkey foreign KEY (group_id) references groups (id),
  constraint group_members_member_id_fkey foreign KEY (member_id) references users (id)
) TABLESPACE pg_default;

create table public.groups (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  bio text null,
  picture text null,
  constraint groups_pkey primary key (id)
) TABLESPACE pg_default;

create table public.groups_messages (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  content text null,
  content_type smallint null,
  sender bigint null,
  group_id bigint null,
  constraint messages_groups_pkey primary key (id),
  constraint messages_groups_group_id_fkey foreign KEY (group_id) references groups (id),
  constraint messages_groups_sender_fkey foreign KEY (sender) references users (id)
) TABLESPACE pg_default;

create table public.likes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  liked_by bigint null,
  post_id bigint null,
  constraint likes_pkey primary key (id),
  constraint likes_liked_by_fkey foreign KEY (liked_by) references users (id),
  constraint likes_post_id_fkey foreign KEY (post_id) references blogs (id)
) TABLESPACE pg_default;

create table public.notifications (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  content text null,
  receiver bigint not null,
  constraint notifications_pkey primary key (id),
  constraint notifications_receiver_fkey foreign KEY (receiver) references users (id)
) TABLESPACE pg_default;

create table public.users (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null default ''::text,
  email text null,
  password text null,
  bio text null default ''::text,
  profile_picture text null,
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email)
) TABLESPACE pg_default;